### ISSUE TITLE
Bug on importing from CheeseFork

### ISSUE THREAD

**Issue by shemadolev** [Vladimir-pa/MyDegree#28]
After pasting the copied courses on the import box, clicking "Import Courses" does nothing.
![image](https://user-images.githubusercontent.com/57037062/72210861-38405600-34ca-11ea-8435-b004858e4368.png)
Tried to import also without the first row (with "X courses, X points") - still doesn't wotk.

**Comment by shemadolev** [comment]
Why did you close this issue? It still doesn't work...

**Comment by Vladimir-pa** [comment]
hm, apparently it stopped working again for some reason, i've closed the issue because i've fixed it that day
